targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      flutter_gen:
        options:
          assets:
            exclude:
              - assets/images/logo_with_background.png