name: search_github_repositories
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  intersperse: ^2.0.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  mockito: ^5.4.5
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  slang_build_runner: ^4.4.0
  isar_generator: ^3.1.0+1

dependency_overrides:
  analyzer: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/